### ISSUE TITLE
App not recognizing if you jump ahead in a folder

### ISSUE THREAD

**Issue by SnorkyMN** [jkoutavas/redweasel#1]
When using arrows or +/- to scroll through pics, if you happen to drag/open a new photo that is further ahead (or behind) in the same folder, then use the arrow or +/- again, it keeps you at whatever you were before you dropped the new photo in, instead of starting to scroll at the new photo dropped in.   I notice that the number in the spot it shows  X of Y, next to the Plus/Minus keys, does not change when you grab the photo that's ahead or behind, it just stays where it is before the new photo is opened.

This is with Redweasel  V 1.0.5 for Windows.

**Comment by jkoutavas** [comment]
Fixed in build 1.0.6
